### PR TITLE
Add overrides to ignore bootstrap and jquery js.

### PR DESCRIPTION
**Pull request by davidlehn**

### CODE REVIEW

**Review by mattcollier — APPROVED** [review]
I like the `main: null` syntax.

**Comment by davidlehn** [comment]
This change works with the current bedrock-views code.  An issue is that if you wanted to use this package and also actually wanted jquery, it's difficult to undo this override.  You'd have to override the override with knowledge of the current jquery package "main" field contents.

**Comment by dlongley** [comment]
> You'd have to override the override with knowledge of the current jquery package "main" field contents.

While not ideal, this is better than everyone having to have secret knowledge to update their configs to not include bootstrap and jquery JS in the default case.

**Review by dlongley — APPROVED** [review]

**Review by dlongley — APPROVED** [review]

**Comment by davidlehn** [comment]
I change this a bit.  Using "browser" vs "main" since it takes precedence and will avoid future issues if jquery or bootstrap added their own browser field.  Also using "false" vs "null" since that seems a bit more in line with what some other tools suggest using.  Though null support also handled in bedrock-views.

**Pull request merged**
